name: go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  windows-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    # wasmtime can't be built with 12.2
    - run: choco install mingw --version 11.2.0.07112021 --allow-downgrade
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - run: go build ./...

  darwin-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - run: go build ./...

  build:
    name: test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: "mysql/mysql-server:8.0"
        env:
          MYSQL_DATABASE: mysql
          MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: mysecretpassword
        ports:
        - 3306:3306

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: install sqlc-gen-test
      run: go install github.com/sqlc-dev/sqlc-gen-test@v0.1.0

    - name: install ./...
      run: go install ./...

    - name: test ./...
      run: gotestsum --junitfile junit.xml -- --tags=examples ./...
      env:
        MYSQL_DATABASE: mysql
        MYSQL_HOST: localhost
        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
        MYSQL_ROOT_PASSWORD: mysecretpassword
        CI_SQLC_PROJECT_ID: ${{ secrets.CI_SQLC_PROJECT_ID }}
        CI_SQLC_AUTH_TOKEN: ${{ secrets.CI_SQLC_AUTH_TOKEN }}
        SQLC_AUTH_TOKEN: ${{ secrets.CI_SQLC_AUTH_TOKEN }}

    - name: build internal/endtoend
      run: go build ./...
      working-directory: internal/endtoend/testdata

    - name: report
      if: ${{ github.ref == 'refs/heads/main' }}
      run: ./scripts/report.sh
      env:
        BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}

  vuln_check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - run: govulncheck ./...