name: Docker

on: [push]
#  push:
#    branches:
#    - master

jobs:

  docker:
    name: Publish to Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build_args: github_ref=${{ github.ref }},github_sha=${{ github.sha }}
        repository: kjconroy/sqlc
        add_git_labels: true
        tags: devel
